 export const FETCH_SENSORS ='FETCH_SENSORS';
<<<<<<< HEAD
 export const FETCH_SEGMENT_LEAKS ='FETCH_SEGMENT_LEAKS';
=======
 export const FETCH_SEGMENTS ='FETCH_SEGMENTS';
 export const FETCH_SEGMENTS_EVENTS = 'FETCH_SEGMENTS_EVENTS';
 export const FETCH_SEGMENTS_LEAKS = 'FETCH_SEGMENTS_LEAKS';
>>>>>>> Dev
